apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  namespace: pipelines-tutorial
spec:
  params:
    - name: url
      type: string
    - name: deleteExisting
      type: string
      default: "false"
  workspaces:
    - name: output
  steps:
    - name: clone
      image: alpine/git
      script: |
        if [ "$(params.deleteExisting)" = "true" ]; then
          rm -rf $(workspaces.output.path)/*
        fi
        git clone $(params.url) $(workspaces.output.path)
